---
volumes:
  caddy-data:
  caddy-config:
  calendar-database:

services:
  caddy:
    image: caddy@sha256:1e40b251ca9639ead7b5cd2cedcc8765adfbabb99450fe23f130eefabf50f4bc
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

  calendar:
    image: ghcr.io/mgnsk/calendar:edge
    build:
      context: .
    command: /bin/calendar
    container_name: calendar
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
      LISTEN_ADDR: ":8080"
      DATABASE_DIR: "/database"
    volumes:
      - calendar-database:/database
