---
volumes:
  calendar-database:


services:
  # TODO: add a HTTPS proxy service
  # Caddyfile:

  # example.com
  # reverse_proxy calendar:8080


  calendar:
    image: ghcr.io/mgnsk/calendar:edge
    build:
      context: .
    command: /calendar
    container_name: calendar
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    env_file: ".env"
    volumes:
      - calendar-database:/database
