---
volumes:
  go-packages:
  go-cache:
  npm-cache:
  caddy-data:
  caddy-config:
  calendar-database:

services:
  caddy:
    image: caddy@sha256:ec18ee54aab3315c22e25f3b2babda73ff8007d39b13b3bd1bfffa2f0444c7d9
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      HOSTNAME: "calendar.localhost"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

  sandbox:
    hostname: calendar
    image: calendar-sandbox
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - uid
        - gid
    init: true
    stdin_open: true
    tty: true
    environment:
      LISTEN_ADDR: ":8080"
      DATABASE_DIR: "/database"
    volumes:
      - ./:/application
      - npm-cache:/home/node/.npm
      - go-packages:/go
      - go-cache:/go-cache
      - calendar-database:/database
