---
volumes:
  caddy-data:
  caddy-config:
  calendar-database:

services:
  caddy:
    image: caddy@sha256:9068f76202c0a03545036d32bf2d424d3b46c1174f254070f605002a2dbc9657
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

  calendar:
    image: ghcr.io/mgnsk/calendar:edge
    build:
      context: .
    command: /bin/calendar
    container_name: calendar
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
      LISTEN_ADDR: ":8080"
      DATABASE_DIR: "/database"
    volumes:
      - calendar-database:/database
