FROM golang:1.24-bookworm@sha256:735c605db83a5e5096eb2cf40aad9d26cbbd45b27dfcd7d30463d0ab0bc92e30 AS go


FROM node:24-bookworm@sha256:cd5857a0ca1fb2c2853dd9b829db9c09f6d4af54a48df033f0da28d5971d1084

COPY --from=go /usr/local/go /usr/local/go

ARG uid
ARG gid

ENV CGO_ENABLED=0
ENV GOPATH="/go"
ENV GOCACHE="/go-cache"
ENV PATH="/go/bin:/usr/local/go/bin:$PATH"

RUN install -d --owner=${uid} --group=${gid} \
    /home/node/.npm \
    /go \
    /go-cache \
    /database

USER ${uid}:${gid}

WORKDIR /application
