---
volumes:
  caddy-data:
  caddy-config:
  calendar-database:

services:
  caddy:
    image: caddy@sha256:25cdc846626b62d05f6b633b9b40c2c9f6ef89b515dc76133cefd920f7dbe562
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

  calendar:
    image: ghcr.io/mgnsk/calendar:edge
    build:
      context: .
    command: /bin/calendar
    container_name: calendar
    restart: unless-stopped
    environment:
      HOSTNAME: "events.example.testing"
      LISTEN_ADDR: ":8080"
      DATABASE_DIR: "/database"
    volumes:
      - calendar-database:/database
