FROM golang:1.25-bookworm@sha256:81dc45d05a7444ead8c92a389621fafabc8e40f8fd1a19d7e5df14e61e98bc1a AS go


FROM node:24-bookworm@sha256:701c8a634cb3ddbc1dc9584725937619716882525356f0989f11816ba3747a22

COPY --from=go /usr/local/go /usr/local/go

ARG uid
ARG gid

ENV CGO_ENABLED=0
ENV GOPATH="/go"
ENV GOCACHE="/go-cache"
ENV PATH="/go/bin:/usr/local/go/bin:$PATH"

RUN install -d --owner=${uid} --group=${gid} \
    /home/node/.npm \
    /go \
    /go-cache \
    /database

USER ${uid}:${gid}

WORKDIR /application
