FROM golang:1.25.5-bookworm@sha256:2c7c65601b020ee79db4c1a32ebee0bf3d6b298969ec683e24fcbea29305f10e AS go


FROM node:25-bookworm@sha256:6d362f0df70431417ef79c30e47c0515ea9066d8be8011e859c6c3575514a027

COPY --from=go /usr/local/go /usr/local/go

ARG uid
ARG gid

ENV CGO_ENABLED=0
ENV GOPATH="/go"
ENV GOCACHE="/go-cache"
ENV PATH="/go/bin:/usr/local/go/bin:$PATH"

RUN install -d --owner=${uid} --group=${gid} \
    /home/node/.npm \
    /go \
    /go-cache \
    /database

USER ${uid}:${gid}

WORKDIR /application
